/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photos = {
  _id: string;
  _type: "photos";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Mixtapes = {
  _id: string;
  _type: "mixtapes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  text?: BlockContent;
  textEng?: BlockContent;
  mixtapes?: Array<{
    title?: string;
    titleEng?: string;
    link?: string;
    _type: "mixtape";
    _key: string;
  }>;
};

export type Editor = {
  _id: string;
  _type: "editor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  features?: Array<{
    title?: string;
    titleEng?: string;
    director?: string;
    detail?: string;
    detailEng?: string;
    year?: number;
    link?: string;
    _type: "feature";
    _key: string;
  }>;
  shorts?: Array<{
    title?: string;
    titleEng?: string;
    director?: string;
    detail?: string;
    detailEng?: string;
    year?: number;
    link?: string;
    _type: "short";
    _key: string;
  }>;
  trailers?: Array<{
    title?: string;
    titleEng?: string;
    link?: string;
    _type: "trailer";
    _key: string;
  }>;
};

export type Director = {
  _id: string;
  _type: "director";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEng?: string;
  slug?: Slug;
  date?: string;
  premiere?: string;
  duration?: number;
  credits?: Array<{
    role?: string;
    roleEng?: string;
    name?: string;
    _type: "credit";
    _key: string;
  }>;
  synopsis?: string;
  synopsisEng?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Info = {
  _id: string;
  _type: "info";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  bio?: BlockContent;
  bioEng?: BlockContent;
  mail?: string;
  instagram?: string;
  vimeoId?: string;
  coverVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = BlockContent | SanityImageAssetReference | Photos | SanityImageCrop | SanityImageHotspot | Mixtapes | Editor | Director | Slug | SanityFileAssetReference | Info | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: DIRECTOR_QUERY
// Query: *[_type == "director"] | order(date desc){    _id,    title,    titleEng,    "slug": slug.current,    date,    premiere,  }
export type DIRECTOR_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  titleEng: string | null;
  slug: string | null;
  date: string | null;
  premiere: string | null;
}>;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: DIRECTOR_BY_SLUG_QUERY
// Query: *[_type == "director" && slug.current == $slug][0]{    _id,    title,    titleEng,    "slug": slug.current,    date,    premiere,    duration,    credits[]{      _key,      role,      roleEng,      name,    },    synopsis,    synopsisEng,    image{      "dimensions": asset->metadata.dimensions,      asset->{        _id,        url      }    }  }
export type DIRECTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  titleEng: string | null;
  slug: string | null;
  date: string | null;
  premiere: string | null;
  duration: number | null;
  credits: Array<{
    _key: string;
    role: string | null;
    roleEng: string | null;
    name: string | null;
  }> | null;
  synopsis: string | null;
  synopsisEng: string | null;
  image: {
    dimensions: SanityImageDimensions | null;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: EDITOR_QUERY
// Query: *[_type == "editor"][0]{    title,    features[]{      _key,      title,      titleEng,      director,       detail,      detailEng,      year,      link    },    shorts[]{      _key,      title,      titleEng,      director,       detail,      detailEng,      year,      link    },    trailers[]{      _key,      title,      titleEng,      link    }  }
export type EDITOR_QUERY_RESULT = {
  title: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    titleEng: string | null;
    director: string | null;
    detail: string | null;
    detailEng: string | null;
    year: number | null;
    link: string | null;
  }> | null;
  shorts: Array<{
    _key: string;
    title: string | null;
    titleEng: string | null;
    director: string | null;
    detail: string | null;
    detailEng: string | null;
    year: number | null;
    link: string | null;
  }> | null;
  trailers: Array<{
    _key: string;
    title: string | null;
    titleEng: string | null;
    link: string | null;
  }> | null;
} | null;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: MIXTAPES_QUERY
// Query: *[_type == "mixtapes"][0]{    _id,    text,    textEng,    mixtapes[]{      _key,      title,      titleEng,      link    }  }
export type MIXTAPES_QUERY_RESULT = {
  _id: string;
  text: BlockContent | null;
  textEng: BlockContent | null;
  mixtapes: Array<{
    _key: string;
    title: string | null;
    titleEng: string | null;
    link: string | null;
  }> | null;
} | null;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: PHOTOS_QUERY
// Query: *[_type == "photos"][0]{    _id,    photos[]{      "dimensions": asset->metadata.dimensions,      _key,      asset->{        _id,        url      }    }  }
export type PHOTOS_QUERY_RESULT = {
  _id: string;
  photos: Array<{
    dimensions: SanityImageDimensions | null;
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
  }> | null;
} | null;

// Source: ../sebastianschjaer-next/src/sanity/queries.ts
// Variable: INFO_QUERY
// Query: *[_type == "info"][0]{    _id,    name,    bio,    bioEng,    mail,    instagram,    vimeoId,    coverVideo{      asset->{        _id,        url      }    },    }
export type INFO_QUERY_RESULT = {
  _id: string;
  name: string | null;
  bio: BlockContent | null;
  bioEng: BlockContent | null;
  mail: string | null;
  instagram: string | null;
  vimeoId: string | null;
  coverVideo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"director\"] | order(date desc){\n    _id,\n    title,\n    titleEng,\n    \"slug\": slug.current,\n    date,\n    premiere,\n  }": DIRECTOR_QUERY_RESULT;
    "*[_type == \"director\" && slug.current == $slug][0]{\n    _id,\n    title,\n    titleEng,\n    \"slug\": slug.current,\n    date,\n    premiere,\n    duration,\n    credits[]{\n      _key,\n      role,\n      roleEng,\n      name,\n    },\n    synopsis,\n    synopsisEng,\n    image{\n      \"dimensions\": asset->metadata.dimensions,\n      asset->{\n        _id,\n        url\n      }\n    }\n  }": DIRECTOR_BY_SLUG_QUERY_RESULT;
    "*[_type == \"editor\"][0]{\n    title,\n    features[]{\n      _key,\n      title,\n      titleEng,\n      director, \n      detail,\n      detailEng,\n      year,\n      link\n    },\n    shorts[]{\n      _key,\n      title,\n      titleEng,\n      director, \n      detail,\n      detailEng,\n      year,\n      link\n    },\n    trailers[]{\n      _key,\n      title,\n      titleEng,\n      link\n    }\n  }": EDITOR_QUERY_RESULT;
    "*[_type == \"mixtapes\"][0]{\n    _id,\n    text,\n    textEng,\n    mixtapes[]{\n      _key,\n      title,\n      titleEng,\n      link\n    }\n  }": MIXTAPES_QUERY_RESULT;
    "*[_type == \"photos\"][0]{\n    _id,\n    photos[]{\n      \"dimensions\": asset->metadata.dimensions,\n      _key,\n      asset->{\n        _id,\n        url\n      }\n    }\n  }": PHOTOS_QUERY_RESULT;
    "*[_type == \"info\"][0]{\n    _id,\n    name,\n    bio,\n    bioEng,\n    mail,\n    instagram,\n    vimeoId,\n    coverVideo{\n      asset->{\n        _id,\n        url\n      }\n    },\n    }": INFO_QUERY_RESULT;
  }
}

